# Generated by Django 4.2.13 on 2024-06-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('service_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('segunda', models.BooleanField(default=False)),
                ('terca', models.BooleanField(default=False)),
                ('quarta', models.BooleanField(default=False)),
                ('quinta', models.BooleanField(default=False)),
                ('sexta', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinhaDeOnibus',
            fields=[
                ('rota_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('rota_numero', models.CharField(max_length=10, unique=True)),
                ('rota_nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('parada_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('referencia_parada', models.TextField()),
                ('parada_latitude', models.FloatField()),
                ('parada_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('viagem_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('destino_letreiro', models.TextField()),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='home.linhadeonibus')),
                ('rota_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_por_numero', to='home.linhadeonibus', to_field='rota_numero')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='home.disponibilidade')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parada', models.IntegerField()),
                ('horario', models.TimeField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='home.parada')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='home.linhadeonibus')),
            ],
        ),
    ]
