# Generated by Django 4.2.13 on 2024-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='service',
            field=models.CharField(max_length=10),
        ),
    ]
