# Generated by Django 4.2.13 on 2024-06-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_viagem_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='rota',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='rota_numero',
            field=models.CharField(max_length=10),
        ),
    ]
