# Generated by Django 4.2.13 on 2024-06-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_viagem_rota_alter_viagem_rota_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioparada',
            name='parada',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='horarioparada',
            name='rota',
            field=models.CharField(max_length=20),
        ),
    ]
