# Generated by Django 4.2.11 on 2024-06-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_horarioparada_parada_alter_horarioparada_rota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarioparada',
            old_name='rota',
            new_name='rota_id',
        ),
        migrations.RenameField(
            model_name='linhadeonibus',
            old_name='rota_id',
            new_name='linha_id',
        ),
        migrations.RenameField(
            model_name='viagem',
            old_name='viagem_id',
            new_name='rota_id',
        ),
    ]
