# Generated by Django 4.2.11 on 2024-06-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_rota_horarioparada_rota_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horarioparada',
            old_name='rota_id',
            new_name='viagem_id',
        ),
        migrations.RenameField(
            model_name='viagem',
            old_name='rota_id',
            new_name='viagem_id',
        ),
    ]
