# Generated by Django 4.2.11 on 2024-06-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_rota_id_horarioparada_viagem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario_Inicio',
            fields=[
                ('viagem_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('horario', models.TimeField()),
            ],
        ),
    ]
