# Generated by Django 4.2.13 on 2024-06-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_horario_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario_inicio',
            name='tempo_intervalo',
            field=models.IntegerField(default=0),
        ),
    ]
