# Generated by Django 4.2.11 on 2024-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_horario_inicio_tempo_intervalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='destino_id',
            field=models.IntegerField(default=0),
        ),
    ]
